# Generated by Django 6.0.6 on 2026-06-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='marks1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject1', models.FloatField()),
                ('subject2', models.FloatField()),
            ],
        ),
    ]
